---
title: "All Survey Info"
author: "Ted Laderas"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
params: 
  survey_name: "BMI 507 Ready for R"
---

```{r setup, include=FALSE}
library(qualtRics)
library(DT)
library(tidyverse)
opts <- list(pageLength =100)

library(tidytext)
library(wordcloud)

build_word_cloud <- function(lab_survey, column){
  
  lab_survey %>%
  select(text={{column}}) %>%
  tidyr::drop_na(text) %>%
  mutate(line=row_number(.)) %>%
  unnest_tokens(output = "word", input = "text") %>%
  dplyr::filter(!word %in% c("elaine", "joel")) %>%
  anti_join(stop_words) %>%
  count(word) %>%
  dplyr::filter(!word %in% c("ted", "dear")) %>%
  with(wordcloud(word, n, max.words = 100))
  
}

```

# Description

This is a pull of the survey information from the "Ready for R" class.



# Pull Survey Data

```{r}
surveys <- all_surveys()
survey_id <- surveys %>% filter(name == params$survey_name) %>%
  pull(id)

survey_id <- "SV_6nc1ZLFMmRoE7nn"

lab_survey <- fetch_survey(survey_id, verbose=TRUE) %>% select(start_date = StartDate, week = Q1, status=Q8, pacing = `Q7_1`, clearest_points = Q2, muddiest_points= Q3, other_stuff=Q4)
```

# Locations

## Locations of Users

Our respondents are from five continents (North America, South America, Europe, Africa, Austrailia, and Central Asia).

```{r}
library(leaflet)

survey <- fetch_survey(survey_id, verbose=TRUE)

leaflet(data = survey) %>% addTiles() %>%
  addMarkers(~LocationLongitude, ~LocationLatitude)
```

# Clearest Points

```{r}
lab_survey %>%
  arrange(desc(start_date)) %>%
  select(week, status, clearest_points) %>%
  DT::datatable(options=opts)
```

```{r}
build_word_cloud(lab_survey, clearest_points)

```

# Muddiest points

```{r}
lab_survey %>% 
  arrange(desc(start_date)) %>%
  select(week, status, muddiest_points) %>% 
  DT::datatable(options=opts)
```

```{r}
build_word_cloud(lab_survey, muddiest_points)

```


# Dear Ted

```{r}
lab_survey %>% 
  arrange(desc(start_date)) %>%
  select(week, status, other_stuff) %>% 
  DT::datatable(options=opts)
```

```{r}
build_word_cloud(lab_survey, other_stuff)

```

```{r}
sentiment_frame <- lab_survey  %>%
  pivot_longer(cols=c(clearest_points, other_stuff), 
               names_to="question", values_to="text") %>%
  select(text, week) %>%
  tidyr::drop_na(text) %>%
  mutate(line=row_number()) %>%
  unnest_tokens(output = "word", input = "text") %>%
  inner_join(get_sentiments("bing")) %>%
  count(index = week, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative) %>%
  filter(index!="Week 7")

ggplot(sentiment_frame, aes(index, sentiment)) +
  geom_col(show.legend = FALSE)

```